apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  KAFKA_HOST: cGtjLWVwOW1tLnVzLWVhc3QtMi5hd3MuY29uZmx1ZW50LmNsb3VkOjkwOTI=
  KAFKA_CLIENT_ID: YmFja2VuZA==
  KAFKA_SASL_USERNAME: TldLU0RaUEdQS0pKWldTRQ==
  KAFKA_SASL_PASSWORD: M2NWS2JDYnY2YjhIMFUxbXIwZVlhYkRobGY3YVNseG5iakJ2MUNVVCsxcmNlQ3JkOEtRVTdVTEhUOVpLT0hLRQ==
  KAFKA_USE_SSL: dHJ1ZQ==
  DB_CONNECTION: bXlzcWw=
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: VWNFZDN3Wmk3Qw==
  DB_HOST: bXlzcWw=
  DB_DATABASE: YmFja2VuZA==
  DB_PORT: MzMwNg==
  

