apiVersion: v1
kind: Secret
metadata:
  name: gateway
type: Opaque
data:
  BOOTSTRAP_SERVERS: cGtjLWVwOW1tLnVzLWVhc3QtMi5hd3MuY29uZmx1ZW50LmNsb3VkOjkwOTI=
  SECURITY_PROTOCOL: U0FTTF9TU0w=
  SASL_MECHANISMS: UExBSU4=
  SASL_USERNAME: TldLU0RaUEdQS0pKWldTRQ==
  SASL_PASSWORD: M2NWS2JDYnY2YjhIMFUxbXIwZVlhYkRobGY3YVNseG5iakJ2MUNVVCsxcmNlQ3JkOEtRVTdVTEhUOVpLT0hLRQ==
  MYSQL_USERNAME: cm9vdA==
  MYSQL_PASSWORD: VWNFZDN3Wmk3Qw==
  MYSQL_HOST: bXlzcWw=
  MYSQL_DATABASE: Z2F0ZXdheQ==

